add more lmao
garretthogan/ayyyylmao pull request #13
Opened 2018-09-28 11:33 UTC by zanuka

2018-09-28 17:00 UTC, dwats requested changes

2018-09-28 17:00 UTC, dwats commented on index.html
> +    const emotes = ['😂', '🔥', '👌', '💯', '🍞', '🐸', '💩', '😆'];
Need to update line 50 otherwise you'll never see the new emojis.

2018-09-28 17:01 UTC, awolden commented
While I am personally a fan of 💩 Is it possible that the usage of this will alienate a large portion of our user base?

2018-09-28 17:17 UTC, seanohollaren commented
I think we have to ask which emojis are truly lit enough to appear on the site.

2018-09-28 21:21 UTC, cpeddecord commented
we should write a bot that can determine the litness of a given emoji, especially within relative proximity of other emojis.

2018-09-28 21:25 UTC, dwats approved these changes

2018-09-28 22:13 UTC, awolden commented
We could have a ML algorithm that scrapes the twitter feed to look for freshest litness.

2018-10-02 21:33 UTC, zanuka commented
so much potential here... good ideas guys 🍶 :: feel free to mod this PR ... yes @awolden  💩 good point about this one, no need to alienate. how about some keyboard commands to add/remove lit emojis based on the litness test / twitter scraper? cmd+shift up == 'increase litness factor' cmd+shift down == 'decrease litness factor'

2018-10-23 09:03 UTC, closed without merging